=== carlabalbontin/MTI-476-Sistemas-y-Aplicaciones-Web/1-XML-y-JSON/investigadores.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema 
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.cbalt.com/mti/investigadores/investigadores.xsd"
	xmlns="http://www.cbalt.com/mti/investigadores" >
	<xs:element name="investigadores">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="investigador" type="tipoInvestigador"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="tipoInvestigador">
		<xs:sequence>
			<xs:element name="nombre" type="xs:string" />
			<xs:element name="apellidos" type="xs:string" />
			<xs:element name="fecha-nacimiento" type="xs:date" />
			<xs:element name="campo" type="xs:string" />
			<xs:element name="nacionalidad" type="xs:string" />
			<xs:element name="educacion">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="titulo" type="tipoTitulo" minOccurs="2" maxOccurs="10"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="publicaciones">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="publicacion" type="tipoPublicacion" minOccurs="2" maxOccurs="1000"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="tipoTitulo">
		<xs:sequence>
			<xs:element name="institucion" type="xs:string" />
			<xs:element name="aÃ±o" type="xs:gYear" />
			<xs:element name="pais" type="xs:string" />
		</xs:sequence>
		<xs:attribute name="tipo" type="xs:string" />
	</xs:complexType>

	<xs:complexType name="tipoPublicacion">
		<xs:sequence>
			<xs:element name="fecha" type="xs:gYear" />
			<xs:element name="titulo" type="xs:string" />
			<xs:element name="publisherName" type="xs:string" />
			<xs:element name="link" type="xs:string" />
			<xs:element name="co-escritores">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="persona" type="tipoPersona" minOccurs="0" maxOccurs="20 "/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="tipoPersona">
		<xs:sequence>
			<xs:element name="nombre" type="xs:string" />
			<xs:element name="apellido" type="xs:string" />
		</xs:sequence>
		<xs:attribute name="nombre" type="xs:string" />
		<xs:attribute name="apellido" type="xs:string" />
	</xs:complexType>

</xs:schema>

=== carlabalbontin/MTI-476-Sistemas-y-Aplicaciones-Web/2-app/info/investigadores.xml
<?xml version="1.0" encoding="UTF-8" ?>
<investigadores 
	xmlns="http://www.cbalt.com/mti/investigadores" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.cbalt.com/mti/investigadores/investigadores.xsd" >
	<investigador>
		<nombre>Camila</nombre>
		<apellidos>Balbontín Tanhnuz</apellidos>
		<fecha-nacimiento>1989-03-27</fecha-nacimiento>
		<foto>http://www.cbalt.com/mti/investigadores/fotos/cbalbontin.jpeg</foto>
		<campo>Ingeniería en Transporte</campo>
		<nacionalidad>Chilena</nacionalidad>
		<educacion>
			<titulo tipo="universitario">
				<campo>Título en Ingeniería Civil</campo>
				<institucion>Pontificia Universidad Católica</institucion>
				<año>2013</año>
				<pais>Chile</pais>
			</titulo>
			<titulo tipo="magister">
				<campo>Magíster en Transporte</campo>
				<institucion>Pontificia Universidad Católica</institucion>
				<año>2013</año>
				<pais>Chile</pais>
			</titulo>
			<titulo tipo="doctorado">
				<campo>Doctorado en Transporte</campo>
				<institucion>University of Sydney</institucion>
				<año>2018</año>
				<pais>Australia</pais>
			</titulo>
		</educacion>
		<publicaciones>
			<publicacion>
				<año>2019</año>
				<titulo>Mobility as a service in community transport, in Australia: can it provide a sustainable future? Transportation Research Part A</titulo>
				<publisherName>Published online</publisherName>
				<link>https://www.sciencedirect.com/science/article/pii/S0965856418311340?via%3Dihub</link>
				<co-escritores>
					<persona nombre="Corinne" apellido="Mulley" />
					<persona nombre="Ho" apellido="Chinh" />
					<persona nombre="David" apellido="Hensher" />
				</co-escritores>
			</publicacion>
			<publicacion>
				<año>2019</año>
				<titulo>Cross-cultural contrasts of preferences for bus rapid transit and light rail transit.</titulo>
				<publisherName>Journal of Transport Economics and Policy</publisherName>
				<co-escritores>
					<persona nombre="David" apellido="Hensher" />
					<persona nombre="Corinne" apellido="Mulley" />
					<persona nombre="Ho" apellido="Chinh" />
				</co-escritores>
			</publicacion>
			<publicacion>
				<año>2019</año>
				<titulo>Do preferences for BRT and LRT change as a voter, citizen, tax payer, or self-interested resident?</titulo>
				<publisherName>Transportation</publisherName>
				<co-escritores>
					<persona nombre="David" apellido="Hensher" />
					<persona nombre="Corinne" apellido="Mulley" />
					<persona nombre="Ho" apellido="Chinh" />
				</co-escritores>
			</publicacion>
		</publicaciones>
	</investigador>
	<investigador>
		<nombre>Constanza</nombre>
		<apellidos>López Lamerain</apellidos>
		<fecha-nacimiento>1985-09-12</fecha-nacimiento>
		<foto>http://www.cbalt.com/mti/investigadores/fotos/clopez.jpeg</foto>
		<campo>Historia de América y Chile</campo>
		<nacionalidad>Chilena</nacionalidad>
		<educacion>
			<titulo tipo="universitario">
				<campo>Título en Historia</campo>
				<institucion>Universidad Adolfo Ibañez</institucion>
				<año>2014</año>
				<pais>Chile</pais>
			</titulo>
			<titulo tipo="magister">
				<campo>Magister en Historia de América y Chile</campo>
				<institucion>Universidad Adolfo Ibañez</institucion>
				<año>2014</año>
				<pais>Chile</pais>
			</titulo>
			<titulo tipo="doctorado">
				<campo>Doctorado en Historia</campo>
				<institucion>Universidad del País Vasco</institucion>
				<año>2020</año>
				<pais>España</pais>
			</titulo>
		</educacion>
		<publicaciones>
			<publicacion>
				<año>2018</año>
				<titulo>Translating canon law into local reality: from Trent to Santiago de Chile</titulo>
				<publisherName>Perspectives historiques, Presses Universitaires de Rennes</publisherName>
				<link>https://www.academia.edu/35870910/L%C3%B3pez_Lamerain_Translating_canon_law.pdf</link>
				<co-escritores>
					<persona nombre="Hugo" apellido="Beauvant" />
					<persona nombre="Thérence" apellido="Carvalho" />
					<persona nombre="Mathilde" apellido="Lemée" />
				</co-escritores>
			</publicacion>
			<publicacion>
				<año>2016</año>
				<titulo>The Third Council of Lima and the unified evangelistic norms in the ecclesiastical province of Peru</titulo>
				<publisherName>Világ-Torténet</publisherName>
				<link>https://www.academia.edu/28430278/A_harmadik_limai_zsinat_%C3%A9s_az_egys%C3%A9ges_evangeliz%C3%A1ci%C3%B3s_rendszab%C3%A1lyok_a_perui_egyh%C3%A1ztartom%C3%A1nyban</link>
			</publicacion>
			<publicacion>
				<año>2011</año>
				<titulo>El Concilio de Trento y Sudamérica: Aplicaciones y adaptaciones en el III Concilio Limense</titulo>
				<publisherName>Anuario de Historia de la Iglesia en Chile</publisherName>
				<link>https://www.academia.edu/7509485/El_Concilio_de_Trento_y_Sudam%C3%A9rica_Aplicaciones_y_adaptaciones_en_el_III_Concilio_Limense</link>
			</publicacion>
			<publicacion>
				<año>2011</año>
				<titulo>El III Concilio de Lima y la conformación de una normativa evangelizadora para la Provincia Eclesiástica del Perú</titulo>
				<publisherName>Intus-Legere Historia</publisherName>
				<link>https://www.academia.edu/2034108/El_III_Concilio_de_Lima_y_la_conformaci%C3%B3n_de_una_normativa_evangelizadora_para_la_Provincia_Eclesi%C3%A1stica_del_Per%C3%BA</link>
			</publicacion>
		</publicaciones>
	</investigador>
</investigadores>

=== carlabalbontin/MTI-476-Sistemas-y-Aplicaciones-Web/1-XML-y-JSON/investigadores.xml
<?xml version="1.0" encoding="UTF-8" ?>
<investigadores 
	xmlns="http://www.cbalt.com/mti/investigadores" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.cbalt.com/mti/investigadores/investigadores.xsd" >
	<investigador>
		<nombre>Camila</nombre>
		<apellidos>Balbontín Tanhnuz</apellidos>
		<fecha-nacimiento>1989-03-27</fecha-nacimiento>
		<campo>Ingeniería en Transporte</campo>
		<nacionalidad>Chilena</nacionalidad>
		<educacion>
			<titulo tipo="universitario">
				<nombre>Ingeniería Civil</nombre>
				<institucion>Pontificia Universidad Católica</institucion>
				<año>2013</año>
				<pais>Chile</pais>
			</titulo>
			<titulo tipo="magister">
				<institucion>Pontificia Universidad Católica</institucion>
				<año>2013</año>
				<pais>Chile</pais>
			</titulo>
			<titulo tipo="doctorado">
				<institucion>University of Sydney</institucion>
				<año>2018</año>
				<pais>Australia</pais>
			</titulo>
		</educacion>
		<publicaciones>
			<publicacion>
				<fecha>2019</fecha>
				<titulo>Mobility as a service in community transport, in Australia: can it provide a sustainable future? Transportation Research Part A</titulo>
				<publisherName>Published online</publisherName>
				<link>https://www.sciencedirect.com/science/article/pii/S0965856418311340?via%3Dihub</link>
				<co-escritores>
					<persona nombre="Corinne" apellido="Mulley" />
					<persona nombre="Ho" apellido="Chinh" />
					<persona nombre="David" apellido="Hensher" />
				</co-escritores>
			</publicacion>
			<publicacion>
				<fecha>2019</fecha>
				<titulo>Cross-cultural contrasts of preferences for bus rapid transit and light rail transit.</titulo>
				<publisherName>Journal of Transport Economics and Policy</publisherName>
				<co-escritores>
					<persona nombre="David" apellido="Hensher" />
					<persona nombre="Corinne" apellido="Mulley" />
					<persona nombre="Ho" apellido="Chinh" />
				</co-escritores>
			</publicacion>
			<publicacion>
				<fecha>2019</fecha>
				<titulo>Do preferences for BRT and LRT change as a voter, citizen, tax payer, or self-interested resident?</titulo>
				<publisherName>Transportation</publisherName>
				<co-escritores>
					<persona nombre="David" apellido="Hensher" />
					<persona nombre="Corinne" apellido="Mulley" />
					<persona nombre="Ho" apellido="Chinh" />
				</co-escritores>
			</publicacion>
		</publicaciones>
	</investigador>
</investigadores>
